/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIDialog: typeof import('./src/components/AIDialog.vue')['default']
    Imageplot: typeof import('./src/components/imageplot.vue')['default']
    MainMenu: typeof import('./src/components/MainMenu.vue')['default']
    MainPage: typeof import('./src/components/MainPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidermenu: typeof import('./src/components/sidermenu.vue')['default']
    Style: typeof import('./src/components/style.vue')['default']
  }
}
